name: benchmark

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Install JMeter
        run: |
          curl https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz --output /tmp/apache-jmeter-5.6.3.tgz
          tar -xvf /tmp/apache-jmeter-5.6.3.tgz
      - run: ./gradlew benchmark
        env:
          JMETER_HOME: /tmp/apache-jmeter-5.6.3
